[idrivee2]
type = s3
provider = IDrive


[e2crypt1]
type = crypt
remote = idrivee2:e2crypt1
filename_encoding = base64


[e2crypt2]
type = crypt
remote = idrivee2:e2crypt2
filename_encoding = base64


[e2crypt3]
type = crypt
remote = idrivee2:e2crypt3
filename_encoding = base64


[e2crypt4]
type = crypt
remote = idrivee2:e2crypt4
filename_encoding = base64

[swissbackup]
type = swift


[sbcrypt1]
type = crypt
remote = swissbackup:sbcrypt1
filename_encoding = base64


[sbcrypt2]
type = crypt
remote = swissbackup:sbcrypt2
filename_encoding = base64
