#!/bin/bash
#
# Set up XDG_CONFIG_HOME
export XDG_CONFIG_HOME="$HOME"/.config
mkdir -p "$XDG_CONFIG_HOME"
mkdir -p "$XDG_CONFIG_HOME"/nixpkgs

# Create symlinks for existing configuration
ln -sf "$PWD/nvim" "$XDG_CONFIG_HOME"/nvim
ln -sf "$PWD/config.nix" "$XDG_CONFIG_HOME"/nixpkgs/config.nix

# Install latest neovim nightly
sh <(curl -L https://raw.githubusercontent.com/nimser/dotfiles/master/scripts/.local/bin/neovim_install.sh)

# Install nix if not available
if ! command -v nix-env &>/dev/null; then
  echo "nix-env command not found. Attempting to install Nix..."
  sh <(curl -L https://nixos.org/nix/install) --daemon --yes
  source /etc/profile.d/nix.sh
fi

# Set system type if not provided via cli
: ${SYSTEM_TYPE:=server}
# Install all packages defined in config.nix
nix-env -iA nixpkgs.myPackages --impure

# configure fish
# configure netplan
