#!/usr/bin/bash

set -euo pipefail

mise_cmd=$(which mise)
if command -v $mise_cmd > /dev/null; then
  $mise_cmd trust && $mise_cmd install
fi
if command -v chezmoi > /dev/null; then
  chezmoi apply
fi
