#!/usr/bin/env -S pkgx +fish -- fish
set -x default_remote swissbackup
set -x rclone_path /usr/bin/rclone

function get_credentials
  set -f credentials_id $argv
  set -f pass_selector (echo $credentials_id)_credentials
  set -f credentials_entry (string split \n (pass rclone/$pass_selector))[1]
  set -f credentials_parts (string split '|' $credentials_entry)
  set -f credentials_keys USER KEY AUTH TENANT PASSWORD
  for i in (seq (count $credentials_parts))
    if test $i -eq 5
      set -gx RCLONE_CONFIG_(string upper $credentials_id)_(echo $credentials_keys[$i]) ($rclone_path obscure $credentials_parts[$i])
    else
      set -gx RCLONE_CONFIG_(string upper $default_remote)_(echo $credentials_keys[$i]) $credentials_parts[$i]
    end
  end
end
for match in (string match -r '[^:]+:' -- $argv)
    set -l remote (string replace -r ':' '' $match)
    get_credentials $remote
end
$rclone_path $argv
