[tools]
chezmoi = "latest"
neovim = "latest"
bat = "latest"
"aqua:tealdeer-rs/tealdeer" = "latest"
make = "latest"
"aqua:sharkdp/fd" = "latest"
"aqua:BurntSushi/ripgrep" = "latest"
"aqua:cli/cli" = "latest"
"aqua:tree-sitter/tree-sitter" = "latest"
"aqua:k9s" = "latest"
"aqua:fish-shell/fish-shell" = "latest"
"ubi:pkgxdev/pkgx" = "latest"
"ubi:pkgxdev/pkgm" = "latest"
direnv = "latest"
